export { default as Develop } from './Develop';
export { default as Facebook } from './Facebook';
export { default as Github } from './Github';
export { default as Link } from './Link';
export { default as LinkedIn } from './LinkedIn';
export { default as Home } from './Home';
export { default as Email } from './Email';
export { default as Play } from './Play';
export { default as Pause } from './Pause';
